### ISSUE TITLE
More detail in regexs 

### ISSUE THREAD

**Issue by MarianoRico** [abyssnlp/Hearst-Hypernym-Extractor#1]
Explain the meaning of the parts of a pattern. For instance, the first pattern:

`(NP_\\w+ (, )?such as (NP_\\w+ ?(, )?(and |or )?)+)','first')`

 what means `NP_\\w+ `
Please, split this pattern in multiple lines to explain its meaning.

**Comment by abyssnlp** [comment]
Added
